Feature branch - Building with Backgrounds and Gradients
Yors-git/Old-Apple-Clone pull request #1
Opened 2020-08-27 15:53 UTC by Yors-git

- Created a clone of an old Apple home page
- We used Flex, Grid, Float for positioning and layout
- We used gradients and background images

2020-08-27 17:16 UTC, krys2fa requested changes
## Awesome job @meronokbay and @Yors-git  👏 
Your project displays good use of semantic HTML as well as CSS classes. 💪 
You have a professional-looking README file as well. 👍 

Please make the following changes to complete the project. They can be seen below:
### Status: Changes Required ♻️ 

- [x] [REQUIRED] You are required to set up code linters in your project directory ([pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/)).
You only have the linter for GitHub actions at the moment.   


Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-08-27 17:16 UTC, krys2fa commented on index.html
> +        </div>
- [x] [REQUIRED] This section should contain four elements which are links (i.e either to other articles or `#`)

2020-08-28 07:51 UTC, Yors-git commented on index.html
> +        </div>
Fixed, we made images act as links

2020-08-28 09:20 UTC, peterrobert approved these changes
### APPROVED :+1: :+1: 
Great work making the changes as requested in the previous review.
Your project is now ready
On to the next one.

### HAPPY CODING :computer:

2020-08-28 12:08 UTC, merged